import {PUBLIC_SERVER_SOCKET,PUBLIC_SERVER_GATEWAY} from '$env/static/public';

export const devEnvironment = {
		PUBLIC_SERVER_SOCKET: PUBLIC_SERVER_SOCKET,
		PUBLIC_SERVER_GATEWAY: PUBLIC_SERVER_GATEWAY
}