import {PUBLIC_SERVER_SOCKET,PUBLIC_SERVER_GATEWAY,PUBLIC_STATIC_USERSFILE,PUBLIC_STATIC_NEWSFILE} from '$env/static/public';
export const devEnvironment = {
		PUBLIC_SERVER_SOCKET: PUBLIC_SERVER_SOCKET,
		PUBLIC_SERVER_GATEWAY: PUBLIC_SERVER_GATEWAY,
		PUBLIC_STATIC_USERSFILE: PUBLIC_STATIC_USERSFILE,
		PUBLIC_STATIC_NEWSFILE: PUBLIC_STATIC_NEWSFILE
}