import {PUBLIC_SERVER_SOCKET,PUBLIC_SERVER_GATEWAY,PUBLIC_SERVER_NGINX,PUBLIC_STATIC_USER} from '$env/static/public';
export const devEnvironment = {
		PUBLIC_SERVER_SOCKET: PUBLIC_SERVER_SOCKET,
		PUBLIC_SERVER_GATEWAY: PUBLIC_SERVER_GATEWAY,
		PUBLIC_SERVER_NGINX: PUBLIC_SERVER_NGINX,
		PUBLIC_STATIC_USER: PUBLIC_STATIC_USER
}